### ISSUE TITLE
Ross Xpression Gateway support

### ISSUE THREAD

**Issue by sfahadshahzad** [maxiboom1/Octopus-connect#1]
Hi,

hope you are doing well.

We are using Ross Xpression graphics and the workflow is pretty straight the designer push the GFX templates to project server and gateway communicates with project server for GFX templates.

Is there any possibility to use with Ross.

Regards,
Fahad

**Comment by maxiboom1** [comment]
Hello Fahad,
Unfortunatelly, this project are focused to write to MSSQL the rundown data, recieved by MOS protocol from Octopus NRCS. I dont think you can use it for Ross expression system.
But anyway, thank you for contacting me!
Alex.
